import type { Metadata } from "next";
import "./globals.css";
import { cn } from "../lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as SonnerTaster } from "@/components/ui/sonner"
import { InnoTeProvider } from "@/stores";

export const metadata: Metadata = {
  title: "InnoTe Editor",
  description: "Generated by @InnoTe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
      )}>
        <InnoTeProvider>
          {children}
        </InnoTeProvider>
      </body>
      <Toaster />
      <SonnerTaster />
    </html>
  );
}
